gustosity/urls.py
from django.conf import settings
from django.contrib import admin
#from django.contrib.auth import views as auth_views
from django.conf.urls.defaults import patterns, include, url
from django.views.generic.simple import direct_to_template

from apps.account.views import UserLikesView, UserActivityView,\
    UserView, UserFollowingView, UserFollowersView
from apps.recipe.views import RecipesListView,\
    RecipeDetailView, RecipeCreateView, RecipeDeleteView,\
    RecipeUpdateView, RecipeForksView, RecipeFansView

# See: https://docs.djangoproject.com/en/dev/ref/contrib/admin/#hooking-adminsite-instances-into-your-urlconf
admin.autodiscover()


# See: https://docs.djangoproject.com/en/dev/topics/http/urls/
urlpatterns = patterns('',
    # API
    (r'^api/', include('apps.api.urls')),

    (r'^search/', include('haystack.urls')),

    # Admin panel and documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),

    # flatpages
    (r'^help/', include('django.contrib.flatpages.urls')),

    # django-registration
    (r'^account/', include('registration.backends.default.urls')),

    # Edit profile
    url(r'^account/edit/$', 'apps.account.views.edit', name='edit_profile'),
    url(r'^login/$', 'django.contrib.auth.views.login', name='auth_login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='auth_logout'),

    # app urls
    (r'^activity/', include('actstream.urls')),

    # Browse recipes section
    # url(r'^r/ingredients/(?P<slug>[-\w]+)/$', RecipesByIngredientListView.as_view(), name='recipes_byingredient'),
    # url(r'^r/ingredients/$', IngredientListView.as_view(), name='view_ingredients'),
    url(r'^r/(?P<filter>[-\w]+)/$', RecipesListView.as_view(), name='recipes_byfilter'),
    url(r'^r/', RecipesListView.as_view(), name='recipe_list'),

    # Upload files
    url(r'^upload/$', 'apps.file_uploader.views.upload'),

    # Contact form
    url(r'^contact/', include("apps.contact_form.urls", namespace="contact_form")),

    # Pricing plans
    url(r'^plans/$', direct_to_template, {'template': 'plans.html'}, name='plans'),

    url(r'', include('social_auth.urls')),

    # User recipes section
    url(r'^new/$', RecipeCreateView.as_view(), name='recipe_new'),
    url(r'^(?P<username>[\.\w]+)/$', UserView.as_view(), name='show_user'),
    url(r'^(?P<username>[\.\w]+)/likes/$', UserLikesView.as_view(), name='user_likes'),
    url(r'^(?P<username>[\.\w]+)/following/$', UserFollowingView.as_view(), name='user_following'),
    url(r'^(?P<username>[\.\w]+)/followers/$', UserFollowersView.as_view(), name='user_followers'),
    url(r'^(?P<username>[\.\w]+)/activity/$', UserActivityView.as_view(), name='user_activity'),
    url(r'^(?P<username>[\.\w]+)/(?P<slug>[-\w]+)/$', RecipeDetailView.as_view(), name='recipe_show'),
    url(r'^(?P<username>[\.\w]+)/(?P<slug>[-\w]+)/delete/$', RecipeDeleteView.as_view(), name='recipe_delete'),
    url(r'^(?P<username>[\.\w]+)/(?P<slug>[-\w]+)/fans/$', RecipeFansView.as_view(), name='recipe_fans'),
    url(r'^(?P<username>[\.\w]+)/(?P<slug>[-\w]+)/forks/$', RecipeForksView.as_view(), name='recipe_forks'),
    url(r'^(?P<username>[\.\w]+)/(?P<slug>[-\w]+)/edit/$', RecipeUpdateView.as_view(), name='recipe_edit'),
    url(r'^(?P<username>[\.\w]+)/(?P<slug>[-\w]+)/fork/$', 'apps.recipe.views.fork', name='ajax-recipe_fork'),

    # Home
    url(r'^$', 'apps.account.views.home', name='home'),

)

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT, 'show_indexes': True}))

gustosity/apps/recipe/models.py
# encoding: utf-8
from django.db import models
from django.db.models.signals import post_save, pre_delete, post_syncdb
from django.utils.translation import ugettext_lazy as _
from django.core.exceptions import ObjectDoesNotExist
from django.dispatch import receiver
from django.contrib.auth.models import User
from django.core.files import File
from django.conf.global_settings import LANGUAGES

from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill, Adjust

from actstream import action

from apps.food.models import Unit
#from apps.food.utils import format_food_unit
from apps.food.helpers import group_by_category
from apps.sluggable.models import SluggableModel

import datetime


class RecipeCategory(SluggableModel):
    """A category of recipe.
    Examples: entree, dessert, side dish.
    """
    name = models.CharField(max_length=100, unique=True)

    class Meta:
        ordering = ['name']
        verbose_name_plural = 'Recipe categories'
        get_latest_by = 'name'

    def __unicode__(self):
        return u'%s' % self.name


def _filter_and_sort_recipes(queryset, kwargs, params):
    SORT_RECIPES_DICT = {
        'rank': '-rank',
        'likes': '-total_likes',
        'views': '-total_views',
        'forks': '-total_forks'
        }
    filterby = kwargs.get('filter', 'default')
    if RecipeCategory.objects.filter(slug=filterby).exists():
        queryset = queryset.filter(category__slug__iexact=filterby)
    elif filterby in Recipe.DIFFICULTIES:
        queryset = queryset.filter(difficulty=filterby)
    sortby = params.get('sortby', 'default')
    if sortby in SORT_RECIPES_DICT:
        queryset = queryset.order_by(SORT_RECIPES_DICT[sortby])

    return filterby, sortby, queryset


class PublicRecipesManager(models.Manager):
    def get_query_set(self):
        return super(PublicRecipesManager, self).get_query_set().filter(is_private=False)


class Recipe(SluggableModel):
    DIFFICULTY_CHOICES = (
        ('easy', _('Easy')),
        ('medium', _('Medium')),
        ('difficult', _('Difficult')),
    )
    DIFFICULTIES = [cat[0] for cat in DIFFICULTY_CHOICES]
    name = models.CharField(max_length=255)
    original = models.ForeignKey('self', blank=True, null=True,
        on_delete=models.SET_NULL, editable=False)
    summary = models.TextField(_(u"Summary"),
        help_text=_(u"Summarize in a sentence or two what this recipe is about."))
    category = models.ForeignKey(RecipeCategory, blank=True, null=True,
        help_text=_("A category of recipe. Examples: entree, dessert, side dish."))
    difficulty = models.CharField(_(u"Level of difficulty"),
        max_length=50, blank=True, null=True,
        choices=DIFFICULTY_CHOICES,
        help_text=_(u"Be honest!"))
    servings = models.PositiveIntegerField(_(u"Servings"),
        blank=True, null=True,
        help_text=_(u"For how many people is this list of ingredients?"))
    tips = models.TextField(_(u"Recipe tips"),
        blank=True, null=True,
        help_text=_(u"Do you have some tips to comment?"))
    prep_minutes = models.IntegerField(_(u"Preparation time"),
        blank=True, null=True,
        help_text=_(u"Time spent gathering, preparing, and mixing the ingredients, in minutes."))
    inactive_prep_minutes = models.IntegerField(_(u"Inactive preparation time"),
        blank=True, null=True,
        help_text=_(u"Time spent waiting, for example when meat is marinating, or bread dough is rising. In minutes."))
    cook_minutes = models.IntegerField(_(u"Cooking time"),
        blank=True, null=True,
        help_text=_(u"Time spent actually cooking or baking, in minutes."))
    num_portions = models.IntegerField("Number of portions", default=1, blank=True, null=True)
    portion = models.CharField(_("Portion name"), max_length=100, blank=True, null=True,
        help_text=_(u"Serving or portion names for recipe yields. Examples: muffin, roll, loaf, serving."))
    source = models.URLField(_('Original source'),
        blank=True, null=True,
        help_text=_('Did you find this recipe somewhere? Be nice with the author.'))
    language = models.CharField(max_length=100, choices=LANGUAGES, blank=True, null=True,
        help_text=_('The language you use to describe the recipe'))
    user = models.ForeignKey(User, related_name='recipes')
    created_at = models.DateTimeField(auto_now_add=True)
    is_private = models.BooleanField(default=False)

    original_image = models.ImageField(u"Main image", upload_to='photos',
        blank=True, null=True)
    formatted_image = ImageSpecField(image_field='original_image', format='JPEG',
            options={'quality': 90})
    thumbnail = ImageSpecField([Adjust(contrast=1.2, sharpness=1.1),
            ResizeToFill(200, 200)], image_field='original_image',
            format='JPEG', options={'quality': 90})
    mini_thumbnail = ImageSpecField([Adjust(contrast=1.2, sharpness=1.1),
            ResizeToFill(90, 70)], image_field='original_image',
            format='JPEG', options={'quality': 90})
    cover = ImageSpecField([Adjust(contrast=1.1, sharpness=1.1),
            ResizeToFill(400, 400)], image_field='original_image',
            format='JPEG', options={'quality': 90})

    rank = models.PositiveIntegerField(_(u"Rank"), default=0, editable=False)

    # denormalized counters for recipe statistics
    total_views = models.PositiveIntegerField(_("Total recipe's views"),
        blank=True, null=True, default=0, db_index=True, editable=False)
    total_likes = models.PositiveIntegerField(_("Total recipe's likes"),
        blank=True, null=True, default=0, db_index=True, editable=False)
    total_forks = models.PositiveIntegerField(_("Total recipe's forks"),
        blank=True, null=True, default=0, db_index=True, editable=False)

    # Managers
    objects = PublicRecipesManager()
    all_objects = models.Manager()

    class Meta:
        db_table = 'gustosity_recipes'
        ordering = ['-created_at']
        get_latest_by = 'created_at'
        unique_together = ('user', 'slug')

    def __unicode__(self):
        return u'%s' % self.name

    def ingredient_groups(self):
        """Return a list of ``(category, [ingredients])`` for this recipe.
        ``category`` is ``None`` for any ingredients without a defined category.
        """
        return group_by_category(self.ingredients.all())

    def update_rank(self):
        likes = Like.recents.filter(recipe=self).count()
        # TODO: afegir paràmetre views i una fòrmula amb decay
        self.rank = likes
        self.save()

    @models.permalink
    def get_absolute_url(self):
        return ('recipe_show', [self.user.username, self.slug])

    def get_other_same_chef(self):
        return Recipe.objects.\
            exclude(pk=self.pk).\
            filter(user=self.user)

    def get_other_same_category(self):
        return Recipe.objects.\
            exclude(pk=self.pk).\
            exclude(user=self.user).\
            filter(category=self.category)

    def get_fans(self):
        users_list = Like.objects.\
            filter(recipe=self, deleted_at=None).\
            values_list('user', flat=True)
        return User.objects.filter(pk__in=users_list)

    def get_forks(self):
        return Recipe.objects.filter(original=self)

    def fork(self, new_user):
        original = Recipe.objects.get(pk=self.pk)
        new_recipe = self
        new_recipe.pk = None
        new_recipe.original = original
        new_recipe.user = new_user
        new_recipe.total_views = 0
        new_recipe.total_likes = 0
        new_recipe.total_forks = 0
        file = File(open(original.original_image.path))
        new_recipe.original_image.save(original.original_image.path, file)

        new_recipe.save()
        for step in original.steps.all():
            step.fork(new_recipe)

        for ingredient in original.ingredients.all():
            ingredient.fork(new_recipe)

        original.total_forks += 1
        original.save()
        return new_recipe


class Step(models.Model):
    recipe = models.ForeignKey(Recipe, related_name='steps')
    description = models.TextField(_(u"Step description"),
        help_text=_(u"Step description"))
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    order = models.PositiveSmallIntegerField(blank=True, null=True,
        default=0, db_index=True, editable=False)

    original_image = models.ImageField(u"Main image", upload_to='photos',
        blank=True, null=True)
    formatted_image = ImageSpecField(image_field='original_image', format='JPEG',
            options={'quality': 90})
    thumbnail = ImageSpecField([Adjust(contrast=1.2, sharpness=1.1),
            ResizeToFill(200, 200)], image_field='original_image',
            format='JPEG', options={'quality': 90})
    mini_thumbnail = ImageSpecField([Adjust(contrast=1.2, sharpness=1.1),
            ResizeToFill(90, 70)], image_field='original_image',
            format='JPEG', options={'quality': 90})
    cover = ImageSpecField([Adjust(contrast=1.1, sharpness=1.1),
            ResizeToFill(400, 400)], image_field='original_image',
            format='JPEG', options={'quality': 90})

    class Meta:
        db_table = 'gustosity_recipe_steps'
        ordering = ['order', '-created_at']
        get_latest_by = 'order'

    def __unicode__(self):
        return u'Step %d - %s' % (self.pk, self.description)

    def save(self, *args, **kwargs):
        try:
            if not self.pk:
                steps = Step.objects.filter(recipe=self.recipe)
                if steps:
                    self.order = steps.latest().order + 1
        except ObjectDoesNotExist:
            pass

        return super(Step, self).save(*args, **kwargs)

    @models.permalink
    def get_absolute_url(self):
        return ('recipe_show', [self.recipe.user.username, self.recipe.slug])

    def fork(self, new_recipe):
        new_step = self
        new_step.pk = None

gustosity/apps/recipe/forms.py
# encoding: utf-8
from django import forms
from apps.recipe.models import Recipe, Step


class RecipeForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'span12'}))
    summary = forms.CharField(required=False, widget=forms.Textarea(attrs={'class': 'span12'}))
    source = forms.CharField(required=False, widget=forms.TextInput(attrs={'class': 'span12'}))
    #servings = forms.CharField(required=False, widget=forms.TextInput(attrs={'class': 'span2'}))
    #num_portions = forms.CharField(required=False, widget=forms.TextInput(attrs={'class': 'span2'}))
    #prep_minutes = forms.CharField(required=False, widget=forms.TextInput(attrs={'class': 'span2'}))
    #cook_minutes = forms.CharField(required=False, widget=forms.TextInput(attrs={'class': 'span2'}))
    #inactive_prep_minutes = forms.CharField(required=False, widget=forms.TextInput(attrs={'class': 'span2'}))

    class Meta:
        model = Recipe
        exclude = ('created_at', 'user', 'username', 'total_views', 'total_likes',
            'slug', 'ingredients', 'tips',)

    def get_form_kwargs(self):
        # pass "user" keyword argument with the current user to your form
        kwargs = super(RecipeForm, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


class RecipeDetailsForm(forms.ModelForm):

    class Meta:
        model = Recipe
        exclude = ('created_at', 'user', 'username', 'total_views', 'total_likes',
            'slug', 'name', 'summary', 'source', 'original_image', 'tips')


class StepForm(forms.ModelForm):
    description = forms.CharField(widget=forms.Textarea(attrs={'class': 'input-xxlarge'}))
    hash = forms.CharField(required=False, widget=forms.HiddenInput())

    class Meta:
        model = Step
        exclude = ('recipe', 'order',)

gustosity/apps/recipe/templates/recipe/_form_input.html
{% load i18n %}
<div class="control-group{% if field.errors %} error{% endif %}">
    <label for="{{ field.auto_id }}" class="required control-label">{{ field.label }}
        {% if field.field.required %}<span class="required">*</span>{% endif %}
    </label>
    <div class="controls">
        {% if field.name == 'original_image' %}
            <span class="btn btn-primary fileinput-button">
                <span>
                    <i class="icon-plus icon-white"></i> {% trans "Select Image" %}
                </span>
                {{ field }}
            </span>
        {% else %}
        {{ field }}
        {% endif %}
        {% if field.help_text %}<span class="info">{{ field.help_text }}</span>{% endif %}
        {% if field.errors %}<label for="{{ field.auto_id }}" class="error">{{ field.errors|join:", " }}</span>{% endif %}
    </div>


</div>

gustosity/apps/recipe/templates/recipe/delete.html
{% extends "base.html" %}


{% block title %}{% endblock %}


{% block content %}
    <h1>{{ recipe }}</h1>
    <p>{{ recipe.summary }}</p>
    <form action="" method="post">
        {% csrf_token %}
        <input type="hidden" name="after" value="{{ recipe.slug }}" />
        <input type="submit" name="delete" value="Remove"/>
    </form>
{% endblock %}

gustosity/apps/recipe/templates/recipe/fans.html
{% extends "base.html" %}
{% load url from future %}
{% load i18n account_tags %}

{% block title %}{% endblock %}


{% block content %}

<div class="row-fluid">

    <div class="span9 blog-detail primary-column">
        <header class="entry-header">
        <h1><a href="{{ recipe.get_absolute_url }}">{{ recipe }}</a> / Fans</h1>
        {% if recipe.source or recipe.original %}
        <div class="entry-meta">
          {% if recipe.original %}<i class="icon-retweet"></i> {% trans "Forked from" %} <a href="{{ recipe.original.get_absolute_url }}">{{ recipe.original }}</a>{% if recipe.source %}<br>{% endif %}{% endif %}
          {% if recipe.source %}{% trans "Source" %}: <a href="{{ recipe.source }}">{{ recipe.source }}</a>{% endif %}
        </div>
        {% endif %}
        {% if recipe.source %}<strong>{% trans "Source" %}:</strong> <a href="{{ recipe.source }}">{{ recipe.source }}</a>{% endif %}

        <div class="byline">
          {% if recipe.category %}{% trans "Category:" %} <a class="btn btn-small btn-very-subtle" href="{% url 'recipes_byfilter' recipe.category.slug %}" title="{% trans "View more recipes with the same category" %}"><i class="icon-tag"></i> {{ recipe.category }}</a>&nbsp;&nbsp;{% endif %}
          {% if recipe.difficulty %}{% trans "Difficulty:" %} <a class="btn btn-small btn-very-subtle" href="{% url 'recipes_byfilter' recipe.difficulty %}" title="{% trans "View more recipes with the same difficulty" %}"><i class="icon-fire"></i> {{ recipe.get_difficulty_display }}</a>{% endif %}
          <span class="pull-right">
          <a class="btn btn-small btn-very-subtle" href="{% url 'recipe_forks' recipe.user.username recipe.slug %}"><i class="icon-retweet"></i> {{ recipe.total_forks }}</a>
          <a class="btn btn-small{% if not recipe|likes:request.user %} btn-very-subtle{% endif %}" href="{% url 'recipe_fans' recipe.user.username recipe.slug %}"><i class="icon-heart"></i> {{ recipe.total_likes }}</a>
          <span class="btn btn-small btn-very-subtle"><i class="icon-eye-open"></i> {{ recipe.total_views }}</span>
          </span>
        </div>
        </header>

        <div class="entry-footer">
          <a href="{{ recipe.user.get_absolute_url }}" title="{% trans "View all recipes by" %} {{ recipe.user }}"><img class="avatar" src="{{ recipe.user.get_avatar_url }}" /></a>
        </div>

        <div class="entry-comments">
            <ul>
            {% for chef in recipe.get_fans %}{% include "account/_user_box.html" %}{% endfor %}
            </ul>
        </div>
    </div>
</div>


{% endblock %}

gustosity/apps/recipe/templates/recipe/forks.html
{% extends "base.html" %}
{% load url from future %}
{% load i18n account_tags %}

{% block title %}{% endblock %}


{% block content %}

<div class="row-fluid">

    <div class="span9 blog-detail primary-column">
        <header class="entry-header">
        <h1><a href="{{ recipe.get_absolute_url }}">{{ recipe }}</a> / Forks</h1>
        {% if recipe.source or recipe.original %}
        <div class="entry-meta">
          {% if recipe.original %}<i class="icon-retweet"></i> {% trans "Forked from" %} <a href="{{ recipe.original.get_absolute_url }}">{{ recipe.original }}</a>{% if recipe.source %}<br>{% endif %}{% endif %}
          {% if recipe.source %}{% trans "Source" %}: <a href="{{ recipe.source }}">{{ recipe.source }}</a>{% endif %}
        </div>
        {% endif %}
        {% if recipe.source %}<strong>{% trans "Source" %}:</strong> <a href="{{ recipe.source }}">{{ recipe.source }}</a>{% endif %}

        <div class="byline">
          {% if recipe.category %}{% trans "Category:" %} <a class="btn btn-small btn-very-subtle" href="{% url 'recipes_byfilter' recipe.category.slug %}" title="{% trans "View more recipes with the same category" %}"><i class="icon-tag"></i> {{ recipe.category }}</a>&nbsp;&nbsp;{% endif %}
          {% if recipe.difficulty %}{% trans "Difficulty:" %} <a class="btn btn-small btn-very-subtle" href="{% url 'recipes_byfilter' recipe.difficulty %}" title="{% trans "View more recipes with the same difficulty" %}"><i class="icon-fire"></i> {{ recipe.get_difficulty_display }}</a>{% endif %}
          <span class="pull-right">
          <a class="btn btn-small btn-very-subtle" href="{% url 'recipe_forks' recipe.user.username recipe.slug %}"><i class="icon-retweet"></i> {{ recipe.total_forks }}</a>
          <a class="btn btn-small{% if not recipe|likes:request.user %} btn-very-subtle{% endif %}" href="{% url 'recipe_fans' recipe.user.username recipe.slug %}"><i class="icon-heart"></i> {{ recipe.total_likes }}</a>
          <span class="btn btn-small btn-very-subtle"><i class="icon-eye-open"></i> {{ recipe.total_views }}</span>
          </span>
        </div>
        </header>

        <div class="entry-footer">
          <a href="{{ recipe.user.get_absolute_url }}" title="{% trans "View all recipes by" %} {{ recipe.user }}"><img class="avatar" src="{{ recipe.user.profile.get_avatar_url }}" /></a>
        </div>

        <div class="entry-comments">
          <ul class="gallery three_col clearfix blog-summary-grid isotope">
            {% for recipe in recipe.get_forks %}{% include "_recipe_box.html" %}{% endfor %}
          </ul>
        </div>
    </div>
</div>

{% endblock %}

gustosity/apps/recipe/templates/recipe/form_edit_recipe.html
{% extends "base.html" %}
{% load url from future %}
{% load i18n %}


{% block content %}

<div class="hero-unit">
    {% if not recipe.pk %}
      <h1>{% trans "Create a new recipe" %}</h1>{% else %}
      <h1><a href="{{ recipe.get_absolute_url }}">{{ recipe }}</a></h1>{% endif %}
</div>


{% if form.errors %}
<div id="form-error">
  <p>{% trans "The operation could not be performed because one or more error(s) occurred." %}<br />{% trans "Please resubmit the form after making the following changes:" %}</p>
  <ul>
  {% for field in form %}
  <li>{{ field.errors|striptags }}</li>
  {% endfor %}
  </ul>
</div>
{% endif %}

<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
<div class="row-fluid contact-page">
  <div class="span5">
    {% include "recipe/_form_input.html" with field=form.name %}
    {% include "recipe/_form_input.html" with field=form.summary %}
    {% include "recipe/_form_input.html" with field=form.source %}
    {% include "recipe/_form_input.html" with field=form.language %}
    {% include "recipe/_form_input.html" with field=form.original_image %}
  </div>

  <div class="span3">

    {% include "recipe/_form_input.html" with field=form.category %}
    {% include "recipe/_form_input.html" with field=form.difficulty %}

    {% include "recipe/_form_input.html" with field=form.servings %}
    {% include "recipe/_form_input.html" with field=form.num_portions %}
    {% include "recipe/_form_input.html" with field=form.portion %}



  </div>

  <div class="span3">
    {% include "recipe/_form_input.html" with field=form.prep_minutes %}
    {% include "recipe/_form_input.html" with field=form.inactive_prep_minutes %}
    {% include "recipe/_form_input.html" with field=form.cook_minutes %}
    {% include "recipe/_form_input.html" with field=form.is_private %}
  </div>
</div>

<div class="row-fluid contact-page">
  <div class="span12">
    <div class="control-group">
      <input class="btn btn-primary btn-large" type="submit" value="save">
    </div>
  </div>
</div>
</form>
{% endblock %}

{% block extracss %}
  <link href="/static/css/jquery.backbone.widgets.css" rel="stylesheet">
  <link href="/static/file-uploader/fineuploader.css" rel="stylesheet">
{% endblock extracss %}


{% block extrajs %}

{% include "recipe/_backbone.html" %}

<script type="text/javascript">
  var urlRecipe = "/api/recipes/{{ recipe.pk }}";
  var recipeId = "{{ recipe.pk }}";
  $(function () {
    new IngredientsEditView();
    $('#id_name').focus();
  });
</script>
{% comment %}
$('textarea.tagged_text').textntags({

    triggers: {
        '@': {
            minChars: 1,
            showImageOrIcon: false,
            uniqueTags: false,
            keys_map: {
                id: 'id',
                title: 'name'
            }
        }
    },

    onDataRequest: function (mode, query, triggerChar, callback) {
        console.log(query);
        $.getJSON(
        url = '/api/ingredients.json', {
            'name': query.toLowerCase()
        },

        function (responseData) {
            query = query.toLowerCase();
            var data = JSON.parse(responseData);
            var found = _.filter(data, function (item) {
                return item.name.toLowerCase().indexOf(query) > -1;
            });
            found.push({
                id: 0,
                type: 'ingredient',
                name: query
            });
            callback.call(this, found);
        });
    }
})
    .bind('tagsAdded.textntags', function (e, addedTagsList) {
    console.log('tagsAdded:' + JSON.stringify(addedTagsList));
})
    .bind('tagsRemoved.textntags', function (e, removedTagsList) {
    console.log('tagsRemoved:' + JSON.stringify(removedTagsList));
});
{% endcomment %}

{% endblock extrajs %}

gustosity/apps/recipe/templates/recipe/ingredients.html
{% extends "base.html" %}
{% load url from future %}
{% load i18n account_tags %}

{% block title %}{% endblock %}


{% block content %}

<div class="row-fluid">
  <ul>
  {% for ingredient in ingredients %}
    <li>{{ ingredient }}</li>
  {% endfor %}
  </ul>
</div>


{% endblock %}

gustosity/apps/recipe/templates/recipe/list.html
{% extends "base.html" %}

{% block title %}Recipes{% endblock %}

{% block content %}
<div class="hero-unit">
    <h1>{{title}}</h1>
</div>
{% include "_browseby.html" %}
{% endblock %}

{% block extrajs %}{% include "_browseby_js.html" %}{% endblock extrajs %}